<a href="https://colab.research.google.com/github/JasmanjotSarna/AI-ML-Learning/blob/main/NumPy_Notes_and_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Basic Array Creation

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
l=([1,2,3],[4,5,6],[7,8,9])

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
a=np.ones((4,8))
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [ ]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation Function

In [ ]:
np.random.rand(10)

array([0.1963408 , 0.33050036, 0.65571351, 0.60735899, 0.6218466 ,
       0.12557643, 0.11355251, 0.57603718, 0.92684017, 0.73120782])

In [ ]:
np.random.randn(10)

array([-0.44077945,  0.65573024, -0.11970161,  1.15209455,  0.65624227,
       -2.13343588,  0.81236428, -0.91188592,  0.1712416 ,  0.23624167])

In [ ]:
np.random.randint(6)

5

In [ ]:
np.random.randint(1,100,10)

array([48, 64,  6, 79, 15,  5, 61, 19, 36,  6])

Array Attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

Array Methods

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)#Sum by Column

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)#Sum by Row

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr.resize(3,10)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

Numpy Indexing and Slicing of Vectors

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[1]

np.int64(12)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr[:5]

array([11, 12, 13, 14, 15])

In [ ]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[1:5:2]

array([12, 14])

In [ ]:
arr[1::2]

array([12, 14, 16, 18, 20])

Numpy Indexing and Slicing of Matrix

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[1,4]

np.int64(10)

In [ ]:
arr[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
arr[1:4,0:2]

array([[ 6,  7],
       [11, 12],
       [16, 17]])

In [ ]:
arr[1:6,0:1]

array([[ 6],
       [11],
       [16],
       [21],
       [26]])

In [ ]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

Boolean Indexing

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Array Operations

Arithmect Operations


In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a=a1+a2
b=a2-a1
c=a1*a2
d=a1/a2
e=a1//a2
f=a1**a2
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[      1     128    6561  262144 9765625]


Broadcasting


In [ ]:
l=[10,20,30,40]
arr=np.array(l)


In [ ]:
arr+10

array([20, 30, 40, 50])

In [ ]:
arr-5

array([ 5, 15, 25, 35])

In [ ]:
arr*2

array([20, 40, 60, 80])

Deep and Shallow Copy

In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [ ]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

Matrix Operations


In [ ]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [ ]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [ ]:
mat1.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

Stacking Array

In [ ]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

In [ ]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]